# Generated by Django 5.2.14 on 2026-06-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='jogadores/'),
        ),
    ]
